routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SubAreaController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\SurveyedController;
use App\Http\Controllers\UserController;
use App\Models\Application;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [SurveyController::class, 'welcomeView'])->name('survey.welcome');

Route::prefix('survey')->group(function () {
    Route::get('/register', [SurveyController::class, 'surveyRegisterView'])->name('survey.register');
    Route::get('/result', [SurveyController::class, 'surveyResultView'])->name('survey.result');
    Route::get('/result-pdf/{application}', [ApplicationController::class, 'show'])->name('survey.resultpdf');
});

Route::get('/form/not-found', [FormController::class, 'notFound'])->name('forms.not-found');
Route::get('/form/apply/{code}', [FormController::class, 'applySurvey'])->name('forms.apply');
Route::get('/form/apply-from-code', [FormController::class, 'applySurveyFromCode'])->name('forms.applyCode');
Route::get('/form/register/{code}', [FormController::class, 'registerSurveyed'])->name('forms.register');
Route::get('/form/result/{code}', [FormController::class, 'showResult'])->name('forms.result');

Route::prefix('admin')->group(function () {
    Route::get('/login', [UserController::class, 'loginView'])->name('admin.users.login');
    Route::post('/login', [UserController::class, 'doLogin'])->name('admin.users.doLogin');
    Route::get('/dashboard', [UserController::class, 'dashboard'])->name('admin.users.dashboard');
    Route::get('/form/auto/{organizationId}', [FormController::class, 'storeAuto'])->name('admin.forms.storeAuto');
    Route::get('/form/share/{id}', [FormController::class, 'share'])->name('admin.forms.share');

    Route::resource('survey', SurveyController::class);
    Route::resource('surveyed', SurveyedController::class);
    Route::resource('answer', AnswerController::class);
    Route::resource('area', AreaController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('sub-area', SubAreaController::class);
    Route::resource('user', UserController::class);
    Route::resource('organization', OrganizationController::class);
    Route::resource('form', FormController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function organizations()
    {
        return $this->hasMany(Organization::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function loginView()
    {
        if(Auth::check()){
            return redirect()->route('admin.users.dashboard');
        }
        return view('admin.users.login');
    }

    public function dashboard()
    {
        return view('admin.users.dashboard');
    }

    public function doLogin(Request $request)
    {
        $validated = $request->validate([
            'email' => 'required|email',
            'password' => 'required|alphaNum'
        ]);

        $data = [
            'email' => $request->get('email'),
            'password' => $request->get('password'),
        ];

        if (Auth::attempt($data)) {
            return redirect()->route('admin.users.dashboard');
        }
        return redirect()->back()
            ->withErrors(['auth' => 'Usuario o contraseña inválidos'])
            ->withInput();
    }
}

resources/views/admin/users/dashboard.blade.php
@extends('layout.admin')
@section('content')
    <div class="container mx-auto p-4">
        <div class="grid grid-cols-1 md:grid-cols-2">
            <a class="flex items-center text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                href="{{ route('organization.index') }}">
                <span class="text-indigo-500 text-2xl mr-2">
                    <x-office />
                </span>
                Organizaciones
            </a>
            <a class="flex items-center text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                href="{{ route('form.index') }}">
                <span class="text-indigo-500 text-2xl mr-2">
                    <x-folder />
                </span>
                Encuestas
            </a>
        </div>

    </div>
@endsection

resources/views/admin/users/form.blade.php
@extends('layout.admin')
@section('content')
    User form
@endsection

resources/views/admin/users/index.blade.php
@extends('layout.admin')
@section('content')
    Users
@endsection

resources/views/admin/users/login.blade.php
@extends('layout.login')
@section('content')
    <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
        Iniciar Sesión
    </h1>
    <form class="space-y-4 md:space-y-6" action="{{route('admin.users.doLogin')}}" method="POST">
        @csrf
        <div>
            <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Correo
                Electrónico</label>
            <input type="email" name="email" id="email"
                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                placeholder="name@company.com" required="">
        </div>
        <div>
            <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Contraseña</label>
            <input type="password" name="password" id="password" placeholder="••••••••"
                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                required="">
        </div>

        <button type="submit"
            class="w-full text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-80">
            Iniciar Sesión
        </button>

    </form>
@endsection