routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SubAreaController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\SurveyedController;
use App\Http\Controllers\UserController;
use App\Models\Application;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [SurveyController::class, 'welcomeView'])->name('survey.welcome');

Route::prefix('survey')->group(function () {
    Route::get('/register', [SurveyController::class, 'surveyRegisterView'])->name('survey.register');
    Route::get('/result', [SurveyController::class, 'surveyResultView'])->name('survey.result');
    Route::get('/result-pdf/{application}', [ApplicationController::class, 'show'])->name('survey.resultpdf');
});

Route::get('/form/not-found', [FormController::class, 'notFound'])->name('forms.not-found');
Route::get('/form/apply/{code}', [FormController::class, 'applySurvey'])->name('forms.apply');
Route::get('/form/apply-from-code', [FormController::class, 'applySurveyFromCode'])->name('forms.applyCode');
Route::get('/form/register/{code}', [FormController::class, 'registerSurveyed'])->name('forms.register');
Route::get('/form/result/{code}', [FormController::class, 'showResult'])->name('forms.result');

Route::prefix('admin')->group(function () {
    Route::get('/login', [UserController::class, 'loginView'])->name('admin.users.login');
    Route::post('/login', [UserController::class, 'doLogin'])->name('admin.users.doLogin');
    Route::get('/dashboard', [UserController::class, 'dashboard'])->name('admin.users.dashboard');
    Route::get('/form/auto/{organizationId}', [FormController::class, 'storeAuto'])->name('admin.forms.storeAuto');
    Route::get('/form/share/{id}', [FormController::class, 'share'])->name('admin.forms.share');

    Route::resource('survey', SurveyController::class);
    Route::resource('surveyed', SurveyedController::class);
    Route::resource('answer', AnswerController::class);
    Route::resource('area', AreaController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('sub-area', SubAreaController::class);
    Route::resource('user', UserController::class);
    Route::resource('organization', OrganizationController::class);
    Route::resource('form', FormController::class);
});

app/Models/Survey.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    use HasFactory;

    public function series()
    {
        return $this->hasMany(Serie::class);
    }

    public function forms()
    {
        return $this->hasMany(Form::class);
    }

    public function getAreas($surveyId)
    {
        return Area::whereHas('serie', function ($query) use ($surveyId) {
            $query->where('survey_id', $surveyId);
        })
            ->with(['serie' => function ($query) {
                $query->orderBy('code', 'ASC');
            }])
            ->get();
    }
}

app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Organization;
use App\Models\Survey;
use Illuminate\Http\Request;

class SurveyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.surveys.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.surveys.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function show(Survey $survey)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function edit(Survey $survey)
    {
        return view('admin.surveys.form');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Survey $survey)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function destroy(Survey $survey)
    {
        //
    }


    public function welcomeView()
    {
        return view('survey.welcome');
    }

    public function surveyRegisterView()
    {
        $organizations = Organization::all();
        return view('survey.register', [
            'organizations' => $organizations
        ]);
    }
}

resources/views/survey/form.blade.php
@extends('layout.survey')
@section('content')
    <x-appbar :title=" $application->round_number . ' Ronda' " />
    <div class="container mx-auto p-4">
        <div class="w-1/3 bg-gray-200 rounded-full h-2.5 dark:bg-gray-700 mb-6">
            <div class="bg-indigo-600 h-2.5 rounded-full" style="width: {{ $progress }}%"></div>
        </div>
        <h1 class="text-md font-bold dark:text-white">Serie de Capacidades: <span class="text-orange-500">{{ $area->serie->name }}</span></h1>
        <h2 class="text-xl font-bold dark:text-white">Area de Madurez: <span class="text-indigo-500">{{ $area->name }}</span></h2>
        <p class="mb-6 text-slate-500">{{ $area->description }}</p>

        <form action="{{ route('answer.store') }}" method="POST">
            @csrf
            <input type="hidden" name="area_id" value="{{$area->id}}">
            <input type="hidden" name="application_id" value="{{$application->id}}">
            <input type="hidden" name="code" value="{{$code}}">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                @foreach ($questions as $item)
                <x-question :id="'question_'. $item->id" :value="$item->id" :title="$item->level->name" name="question_id" :description="$item->question" />
            @endforeach
            </div>

            <div class="flex items-center justify-between mt-4">
                <a href="{{ url('/') }}"
                    class="text-center py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-indigo-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Cancelar</a>
                <button type="submit"
                    class="text-center text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-800">Continuar</button>
            </div>
        </form>
    </div>
@endsection

resources/views/survey/register.blade.php
@extends('layout.survey')
@section('content')
    <x-appbar title="Datos del Encuestado" />
    <div class="container p-4 mx-auto">
        <form action="{{ route('surveyed.store') }}" method="POST">
            @csrf
            <input type="hidden" name="organization_id" value="{{ $organization->id }}">
            <input type="hidden" name="form_code" value="{{ $code }}">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="mb-3">
                    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Nombres y
                        Apellidos</label>
                    <input type="text" id="name" name="name" maxlength="255"
                        class=" bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="Juan Perez" required>
                </div>
                <div class="mb-3">
                    <label for="code"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">DNI</label>
                    <input type="text" id="code" name="code" maxlength="8"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="12345678" required>
                </div>
            </div>
            <div class="flex items-center justify-end">
                <button
                    class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-indigo-600 dark:hover:bg-indigo-700 dark:focus:ring-indigo-800">Continuar</button>
            </div>
        </form>
    </div>
@endsection

resources/views/survey/result-pdf.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Resultado de la Encuesta BIM</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <style>
        .border {
            border-width: 1px;
            border-style: solid;
        }

        .border-blue-800 {
            border-color: rgb(30,64,175);
        }

        .bg-blue-700 {
            background-color: rgb(29,78,216);
        }

        .text-white {
            color: #fff
        }

        .uppercase {
            text-transform: uppercase;
        }

        .px-3 {
            padding-left: 0.25rem;
            padding-right: 0.25rem;
        }

        .py-2 {
            padding-top: 0.25rem;
            padding-bottom: 0.25rem;
        }

        .border-slate-300 {
            border-color: rgb(203,213,225);
        }

        .text-center {
            text-align: center;
        }

        table {
            border-collapse: collapse;
        }
        th, td {
            font-size: 13px;
        }
        .w-full {
            width: 19cm;
        }
    </style>
</head>

<body>
    <table class="w-full">
        <thead>
            <tr id="application_{{ $application->id }}" class="bg-blue-700 text-white">
                <th class="border border-blue-800 px-3 py-2 uppercase" colspan="{{ count($levels) + 3 }}">
                    {{ $application->surveyed->name }}
                </th>
            </tr>
            <tr class="bg-blue-700 text-white">
                <th rowspan="2" class="border border-blue-800 px-3 py-2">SERIE DE CAPACIDADES</th>
                <th rowspan="2" class="border border-blue-800 px-3 py-2">ÁREA DE MADUREZ</th>
                <th colspan="{{ count($levels) }}" class="border border-blue-800 px-3 py-2">NIVEL Y
                    VALOR</th>
                <th rowspan="2" class="border border-indigo-300 px-3 py-2">ÍNDICE DE MADUREZ</th>
            </tr>
            <tr class="bg-blue-700 text-white">
                @foreach ($levels as $level)
                    <th class="border border-blue-800 px-3 py-2">{{ $level->name }}
                        ({{ $level->score }})
                    </th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @php
                $areasCount = 0;
            @endphp
            @foreach ($series as $keySerie => $serie)
                @foreach ($serie->areas as $keyArea => $area)
                    @php
                        $areasCount++;
                    @endphp
                    <tr>
                        @if ($keyArea == 0)
                            <td rowspan="{{ count($serie->areas) }}" class="border border-slate-300 px-3 py-2">
                                {{ $serie->name }}</td>
                        @endif
                        <td class="border border-slate-300 px-3 py-2">{{ $area->name }}</td>
                        @foreach ($levels as $level)
                            <td class="border border-slate-300 px-3 py-2 text-center">
                                @foreach ($application->answers as $answer)
                                    @if ($answer->area_id == $area->id && $answer->question->level_id == $level->id)
                                        {{ $answer->score }}
                                    @endif
                                @endforeach
                            </td>
                        @endforeach
                        @if ($keyArea == 0)
                            <td rowspan="{{ count($serie->areas) }}"
                                class="border border-slate-300 px-3 py-2 text-center">
                                @php
                                    $serieAverage = 0;
                                    foreach ($levels as $level) {
                                        foreach ($application->answers as $answer) {
                                            foreach ($serie->areas as $areaTmp) {
                                                if ($answer->area_id == $areaTmp->id && $answer->question->level_id == $level->id) {
                                                    $serieAverage = $serieAverage + $answer->score;
                                                }
                                            }
                                        }
                                    }
                                    $serieAverage = $serieAverage / count($serie->areas);
                                @endphp
                                {{ round($serieAverage, 2) }}
                            </td>
                        @endif
                    </tr>
                @endforeach
            @endforeach
            <tr class="font-bold">
                <td class="border border-slate-300 px-3 py-2 text-center" colspan="2">VALOR POR NIVEL
                    DE MADUREZ</td>
                @php
                    $levelsSum = 0;
                @endphp
                @foreach ($levels as $level)
                    <td class="border border-slate-300 px-3 py-2 text-center">
                        @php
                            $levelSum = 0;
                            foreach ($application->answers as $answer) {
                                if ($answer->question->level_id == $level->id) {
                                    $levelSum += $answer->score;
                                }
                            }
                            $levelsSum += $levelSum;
                        @endphp
                        {{ $levelSum }}
                    </td>
                @endforeach
                <td class="border border-slate-300 px-3 py-2 text-center">{{ $levelsSum }}</td>
            </tr>
            <tr class="font-bold text-blue-700">
                <td class="border border-slate-300 px-3 py-2 text-center" colspan="{{ count($levels) + 2 }}">ÍNDICE DE
                    MADUREZ BIM</td>
                <td class="border border-slate-300 px-3 py-2 text-center">
                    {{ round($levelsSum / $areasCount, 2) }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>

resources/views/survey/result.blade.php
@extends('layout.survey')
@section('content')
    <div class="container p-4 mx-auto">

        <div class="flex items-center justify-center mt-6 mb-6">
            <img src="{{asset('images/checked.svg')}}" alt="success" class="w-32 h-32">
        </div>

        <p class="text-center mb-4 text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">
            Encuesta finalizada. <br>
            El nivel de adopción BIM es:
        </p>
        <h1 class="text-center mb-4 text-5xl font-extrabold tracking-tight leading-none text-indigo-500 dark:text-indigo-300">
            {{$label}}
        </h1>
        <p class="text-center mb-8 text-lg font-normal text-blue-500 lg:text-xl dark:text-gray-400 mb-6">
            Indice de Madurez <br>
            <span class="text-3xl font-bold">{{round($value, 2)}}</span>
        </p>

        <div class="flex items-center justify-center">
            <a href="{{route('survey.welcome')}}" class="text-center py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-indigo-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Ir al Inicio</a>
            <a target="_blank" href="{{route('survey.resultpdf',['application' => $id])}}" class="text-center text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-800">Descargar PDF</a>
        </div>

    </div>
@endsection