routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SubAreaController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\SurveyedController;
use App\Http\Controllers\UserController;
use App\Models\Application;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [SurveyController::class, 'welcomeView'])->name('survey.welcome');

Route::prefix('survey')->group(function () {
    Route::get('/register', [SurveyController::class, 'surveyRegisterView'])->name('survey.register');
    Route::get('/result', [SurveyController::class, 'surveyResultView'])->name('survey.result');
    Route::get('/result-pdf/{application}', [ApplicationController::class, 'show'])->name('survey.resultpdf');
});

Route::get('/form/not-found', [FormController::class, 'notFound'])->name('forms.not-found');
Route::get('/form/apply/{code}', [FormController::class, 'applySurvey'])->name('forms.apply');
Route::get('/form/apply-from-code', [FormController::class, 'applySurveyFromCode'])->name('forms.applyCode');
Route::get('/form/register/{code}', [FormController::class, 'registerSurveyed'])->name('forms.register');
Route::get('/form/result/{code}', [FormController::class, 'showResult'])->name('forms.result');

Route::prefix('admin')->group(function () {
    Route::get('/login', [UserController::class, 'loginView'])->name('admin.users.login');
    Route::post('/login', [UserController::class, 'doLogin'])->name('admin.users.doLogin');
    Route::get('/dashboard', [UserController::class, 'dashboard'])->name('admin.users.dashboard');
    Route::get('/form/auto/{organizationId}', [FormController::class, 'storeAuto'])->name('admin.forms.storeAuto');
    Route::get('/form/share/{id}', [FormController::class, 'share'])->name('admin.forms.share');

    Route::resource('survey', SurveyController::class);
    Route::resource('surveyed', SurveyedController::class);
    Route::resource('answer', AnswerController::class);
    Route::resource('area', AreaController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('sub-area', SubAreaController::class);
    Route::resource('user', UserController::class);
    Route::resource('organization', OrganizationController::class);
    Route::resource('form', FormController::class);
});

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use App\Models\Application;
use App\Models\Area;
use App\Models\Form;
use App\Models\Level;
use App\Models\Organization;
use App\Models\Question;
use App\Models\Serie;
use App\Models\Survey;
use App\Models\Surveyed;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Organization::where('user_id', Auth::user()->id)->with('forms')->get();
        return view('admin.forms.index', [
            'organizations' => $items
        ]);
    }

    public function share(Request $request, $id)
    {
        return view('admin.forms.share', [
            'item' => Form::find($id)
        ]);
    }

    public function notFound()
    {
        return view('admin.forms.not-found');
    }

    public function applySurveyFromCode(Request $request)
    {
        return redirect()->route('forms.apply', ['code' => $request->get('code')]);
    }

    public function registerSurveyed(Request $request, $code)
    {
        $form = Form::where('code', $code)->with('organization')->first();

        if (!$form) {
            return redirect()->route('forms.not-found');
        }

        return view('survey.register', [
            'organization' => $form->organization,
            'code' => $code
        ]);
    }

    public function applySurvey(Request $request, $code)
    {
        if (!$request->session()->has('surveyedId') || !Surveyed::find(session('surveyedId'))) {
            $request->session()->forget('surveyedId');
            return redirect()->route('forms.register', ['code' => $code]);
        }

        $form = Form::where('code', $code)->first();

        if (!$form) {
            return redirect()->route('forms.not-found');
        }

        $application = (new Application())->getOrCreate($request->session()->get('surveyedId'), $form->id);

        if ($application->status == 1) {
            return redirect()->route('forms.result', ['code' => $code]);
        }

        $content = (new Application())->getFormContent($application->id);
        if ($content != null) {
            $content['code'] = $code;
            return view('survey.form', $content);
        }

        return redirect()->route('forms.result', ['code' => $code]);
    }

    public function showResult(Request $request, $code)
    {
        $form = Form::where('code', $code)->first();

        if (!$form) {
            return redirect()->route('forms.not-found');
        }
        $application = Application::where('surveyed_id', session('surveyedId'))
            ->where('form_id', $form->id)
            ->orderBy('created_at', 'DESC')
            ->first();

        if (!$application) {
            $request->session()->forget('surveyedId');
            return redirect()->route('forms.register', ['code' => $code]);
        }

        $result = (new Application())->getResult($application->id);

        if ($result['value'] == 0.0) {
            return redirect()->route('forms.apply', ['code' => $code]);
        }

        $result['id'] = $application->id;

        if ($application->status == 0) {
            $application->status = 1;
            $application->save();
        }

        $request->session()->forget('surveyedId');
        return view('survey.result', $result);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    public function storeAuto(Request $request, $organizationId)
    {
        $survey = Survey::first();
        $item = (new Form())->generateForm($organizationId, $survey->id);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function show(Form $form)
    {

        return view('admin.forms.result', [
            'form' => $form,
            'series' => Serie::where('survey_id', $form->survey_id)->get(),
            'levels' => Level::all(),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function edit(Form $form)
    {
        $maxRoundApplication = $form->applications()->max('round_number');
        return view('admin.forms.edit', [
            'form' => $form,
            'maxRoundApplication' => $maxRoundApplication || 1
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Form $form)
    {
        $form->description = $request->get('description');
        $form->rounds = $request->get('rounds');
        $form->save();
        return redirect()->route('form.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function destroy(Form $form)
    {
        $form->delete();
        return redirect()->route('form.index');
    }
}

resources/views/admin/forms/edit.blade.php
@extends('layout.admin')
@section('content')
    <div class="container mx-auto px-4">
        <nav class="flex py-4 mb-4" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
                <li class="inline-flex items-center">
                    <a href="{{ route('admin.users.dashboard') }}"
                        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                        <x-home />
                        Inicio
                    </a>
                </li>
                <li aria-current="page">
                    <div class="flex items-center">
                        <x-chevron-right />
                        <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">Modificar Encuesta</span>
                    </div>
                </li>
            </ol>
        </nav>
        <form action="{{ route('form.update',['form' => $form->id]) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                    <label for="description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        Descripción
                    </label>
                    <input type="text" name="description" id="description"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="Encuesta BIM" value="{{$form->description}}" required="">
                </div>
                <div>
                    <label for="rounds" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        Cantidad de Rondas
                    </label>
                    <input type="number" name="rounds" id="rounds"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="3" min="{{$maxRoundApplication}}" value="{{$form->rounds}}" required="">
                </div>
            </div>
            <button type="submit"
                class="w-full text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-80">
                Guardar
            </button>
        </form>
    </div>
@endsection

resources/views/admin/forms/index.blade.php
@extends('layout.admin')
@section('content')
    <div class="container mx-auto px-4">
        <nav class="flex py-4 mb-4" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
                <li class="inline-flex items-center">
                    <a href="{{ route('admin.users.dashboard') }}"
                        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                        <x-home />
                        Inicio
                    </a>
                </li>
                <li aria-current="page">
                    <div class="flex items-center">
                        <x-chevron-right />
                        <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">
                            Encuestas
                        </span>
                    </div>
                </li>
            </ol>
        </nav>

        @foreach ($organizations as $org)
            <div class="p-4 mb-4">
                <div class="flex items-center justify-between mb-4">
                    <h1 class="text-medium flex-1 font-bold dark:text-white">{{ $org->name }}</h1>
                    <a href="{{ route('admin.forms.storeAuto', ['organizationId' => $org->id]) }}"
                        class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-indigo-600 dark:hover:bg-indigo-700 dark:focus:ring-indigo-800">
                        Nueva Encuesta
                    </a>
                </div>
                @foreach ($org->forms as $item)
                    <div class="border-slate-300 dark:border-slate-800 dark:bg-slate-800 border rounded p-3 mb-4">
                        <div class="flex justify-between">
                            <div class="flex-1">
                                <h2 class="text-medium font-bold dark:text-white">{{ $item->description }}</h2>
                                <p class="text-sm font-bold text-slate-500">{{$item->code}}</p>
                                <span class="text-sm font-bold text-blue-500 dark:text-blue-300">{{ $item->rounds }}
                                    Ronda(s)</span>
                            </div>
                            <div class="flex">
                                <a href="{{ route('form.edit', ['form' => $item->id]) }}"
                                    class="text-gray-800 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-2 py-1 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                                    <x-pencil-square />
                                </a>

                                <form id="form_delete_{{ $item->id }}"
                                    action="{{ route('form.destroy', ['form' => $item->id]) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                </form>

                                <button onclick="confirmDelete('form_delete_{{ $item->id }}')"
                                    class="btn-delete text-pink-500 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-2 py-1 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                                    <x-trash />
                                </button>
                            </div>
                        </div>
                        <p class="text-sm text-slate-800 mt-2 mb-4">Registrada el
                            {{ $item->created_at->format('d/m/Y H:i') }}
                        </p>
                        <div class="flex items-center justify-between md:justify-end">
                            <a href="{{ route('admin.forms.share', ['id' => $item->id]) }}"
                                class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-2 py-1 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                                <span class="text-blue-500 mr-2">
                                    <x-share />
                                </span>
                                Compartir
                            </a>
                            <a href="{{route('form.show',['form' => $item->id])}}"
                                class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-2 py-1 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                                <span class="text-green-500 mr-2">
                                    <x-eye />
                                </span>
                                Ver Resultados
                            </a>

                        </div>
                    </div>
                @endforeach

            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/forms/not-found.blade.php
@extends('layout.survey')
@section('content')
    <div class="container mx-auto p-6">
        <h1 class="text-center text-2xl font-bold">Encuesta no encontrada</h1>
        <p class="text-center text-slate-500">
            Es probable que la encuesta haya sido eliminada o ya no está disponible
            <br>
            <br>
            <a href="{{ url('/') }}"
            class="text-center mx-auto text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-800">Ingresar otro Código</a>
        </p>

    </div>
@endsection

resources/views/admin/forms/share.blade.php
@extends('layout.admin')
@section('content')
    <div class="container mx-auto px-4">
        <nav class="flex py-4 mb-4" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
                <li class="inline-flex items-center">
                    <a href="{{ route('admin.users.dashboard') }}"
                        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                        <x-home />
                        Inicio
                    </a>
                </li>
                <li aria-current="page">
                    <div class="flex items-center">
                        <x-chevron-right />
                        <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">
                            Compartir Encuesta
                        </span>
                    </div>
                </li>
            </ol>
        </nav>

        <div class="mb-4">
            <h1 class="font-bold text-lg mb-4 dark:text-white">Compartir Enlace por</h1>
            <a href="https://wa.me/?text=Hola%2C%20te%20env%C3%ADo%20el%20enlace%20para%20rellenar%20la%20encuesta%20BIM%0A{{route('forms.apply',['code' => $item->code])}}" target="_blank"
                class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                <span class="text-green-500 mr-2">
                    <x-whatsapp />
                </span>
                WhatsApp
            </a>
            <a href="mailto:?body=Hola%2C%20te%20env%C3%ADo%20el%20enlace%20para%20rellenar%20la%20encuesta%20BIM%0A{{route('forms.apply',['code' => $item->code])}}"
                class="text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                <span class="text-red-500 mr-2">
                    <x-email />
                </span>
                Correo
            </a>
        </div>

        <div class="mb-4">
            <h1 class="font-bold text-lg mb-4 dark:text-white">Copiar Código</h1>
            <div class="flex items-center justify-between gap-4">
                <input type="text" value="{{ $item->code }}"
                    class="text-copy-code grow bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"readonly>
                <button onclick="copyToClipboard('{{$item->code}}')"
                    class="btn-copy-code flex-none whitespace-nowrap text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-80">
                    <x-clipboard />
                </button>
            </div>
        </div>

        <div id="toast"
            class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800"
            role="alert">
            <span class="font-medium">Código Copiado</span> Puedes compartir el código de la encuesta para que sea
            contestada.
        </div>
    </div>
    <script>
        function copyToClipboard(str) {
            const el = document.createElement('textarea');
            el.value = str;
            el.setAttribute('readonly', '');
            el.style.position = 'absolute';
            el.style.left = '-9999px';
            document.body.appendChild(el);
            el.select();
            document.execCommand('copy');
            document.body.removeChild(el);
            document.getElementById('toast').classList.remove('hidden');
            hideToast();
        }

        function hideToast(){
            setTimeout(function(){
                document.getElementById('toast').classList.add('hidden');
            }, 2000);
        }
        copyToClipboard("{{ $item->code }}");
        hideToast();
    </script>
@endsection