routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SubAreaController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\SurveyedController;
use App\Http\Controllers\UserController;
use App\Models\Application;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [SurveyController::class, 'welcomeView'])->name('survey.welcome');

Route::prefix('survey')->group(function () {
    Route::get('/register', [SurveyController::class, 'surveyRegisterView'])->name('survey.register');
    Route::get('/result', [SurveyController::class, 'surveyResultView'])->name('survey.result');
    Route::get('/result-pdf/{application}', [ApplicationController::class, 'show'])->name('survey.resultpdf');
});

Route::get('/form/not-found', [FormController::class, 'notFound'])->name('forms.not-found');
Route::get('/form/apply/{code}', [FormController::class, 'applySurvey'])->name('forms.apply');
Route::get('/form/apply-from-code', [FormController::class, 'applySurveyFromCode'])->name('forms.applyCode');
Route::get('/form/register/{code}', [FormController::class, 'registerSurveyed'])->name('forms.register');
Route::get('/form/result/{code}', [FormController::class, 'showResult'])->name('forms.result');

Route::prefix('admin')->group(function () {
    Route::get('/login', [UserController::class, 'loginView'])->name('admin.users.login');
    Route::post('/login', [UserController::class, 'doLogin'])->name('admin.users.doLogin');
    Route::get('/dashboard', [UserController::class, 'dashboard'])->name('admin.users.dashboard');
    Route::get('/form/auto/{organizationId}', [FormController::class, 'storeAuto'])->name('admin.forms.storeAuto');
    Route::get('/form/share/{id}', [FormController::class, 'share'])->name('admin.forms.share');

    Route::resource('survey', SurveyController::class);
    Route::resource('surveyed', SurveyedController::class);
    Route::resource('answer', AnswerController::class);
    Route::resource('area', AreaController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('sub-area', SubAreaController::class);
    Route::resource('user', UserController::class);
    Route::resource('organization', OrganizationController::class);
    Route::resource('form', FormController::class);
});

app/Models/Organization.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function forms()
    {
        return $this->hasMany(Form::class);
    }

    public function surveyeds()
    {
        return $this->hasMany(Surveyed::class);
    }

    public function checkIfExists($code): bool
    {
        return $this->where('code', $code)->first() != null;
    }

    public function getTypes() {
        return [
            'PRIVATE' => 'Privada',
            'PUBLIC' => 'Pública'
        ];
    }
}

app/Http/Controllers/OrganizationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Organization;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrganizationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Organization::where('user_id', Auth::user()->id)->get();
        return view('admin.organizations.index', [
            'organizations' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.organizations.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $item = new Organization();
        $item->name = $request->get('name');
        $item->code = $request->get('code');
        $item->type = $request->get('type');
        $item->user_id = Auth::user()->id;
        $item->save();

        return redirect()->route('organization.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function show(Organization $organization)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function edit(Organization $organization)
    {
        return view('admin.organizations.edit', ['item' => $organization]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Organization $organization)
    {
        $organization->name = $request->get('name');
        $organization->code = $request->get('code');
        $organization->type = $request->get('type');
        $organization->save();

        return redirect()->route('organization.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function destroy(Organization $organization)
    {
        $organization->delete();
        return redirect()->route('organization.index');
    }
}

resources/views/admin/organizations/edit.blade.php
@extends('layout.admin')
@section('content')
    <div class="container mx-auto px-4">
        <nav class="flex py-4 mb-4" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
                <li class="inline-flex items-center">
                    <a href="{{ route('admin.users.dashboard') }}"
                        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                        <x-home />
                        Inicio
                    </a>
                </li>
                <li aria-current="page">
                    <div class="flex items-center">
                        <x-chevron-right />
                        <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">Editar
                            Organización</span>
                    </div>
                </li>
            </ol>
        </nav>
        <form action="{{ route('organization.update',['organization' => $item->id]) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        Nombre / Razón Social
                    </label>
                    <input type="text" name="name" id="name"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="ABC S.A.C" value="{{$item->name}}" required="">
                </div>
                <div>
                    <label for="code" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        R.U.C
                    </label>
                    <input type="number" min="0" name="code" id="code"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="12345678912" value="{{$item->code}}" required="">
                </div>
                <div>
                    <label for="type" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">
                        Tipo
                    </label>
                    <select id="type" name="type"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <option value="Privada" @if($item->type == 'Privada') selected @endif>Privada</option>
                        <option value="Pública" @if($item->type == 'Pública') selected @endif>Pública</option>
                    </select>
                </div>
            </div>
            <button type="submit"
                class="w-full text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-80">
                Guardar
            </button>
        </form>
    </div>
@endsection

resources/views/admin/organizations/form.blade.php
@extends('layout.admin')
@section('content')
    <div class="container mx-auto px-4">
        <nav class="flex py-4 mb-4" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
                <li class="inline-flex items-center">
                    <a href="{{ route('admin.users.dashboard') }}"
                        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                        <x-home />
                        Inicio
                    </a>
                </li>
                <li aria-current="page">
                    <div class="flex items-center">
                        <x-chevron-right />
                        <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">Registrar
                            Organización</span>
                    </div>
                </li>
            </ol>
        </nav>
        <form action="{{ route('organization.store') }}" method="POST">
            @csrf
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        Nombre / Razón Social
                    </label>
                    <input type="text" name="name" id="name"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="ABC S.A.C" required="">
                </div>
                <div>
                    <label for="code" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        R.U.C
                    </label>
                    <input type="number" min="0" name="code" id="code"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500"
                        placeholder="12345678912" required="">
                </div>
                <div>
                    <label for="type" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">
                        Tipo
                    </label>
                    <select id="type" name="type"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <option value="Privada">Privada</option>
                        <option value="Pública">Pública</option>
                    </select>
                </div>
            </div>
            <button type="submit"
                class="w-full text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-80">
                Guardar
            </button>
        </form>
    </div>
@endsection

resources/views/admin/organizations/index.blade.php
@extends('layout.admin')
@section('content')
    <div class="container mx-auto px-4">
        <div class="flex items-center justify-between mb-4">
            <nav class="flex py-4 flex-1" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-3">
                    <li class="inline-flex items-center">
                        <a href="{{ route('admin.users.dashboard') }}"
                            class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                            <x-home />
                            Inicio
                        </a>
                    </li>
                    <li aria-current="page">
                        <div class="flex items-center">
                            <x-chevron-right />
                            <span
                                class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">Organizaciones</span>
                        </div>
                    </li>
                </ol>
            </nav>

            <a href="{{ route('organization.create') }}"
                class="text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-indigo-600 dark:hover:bg-indigo-700 dark:focus:ring-indigo-800">
                Nueva Organización
            </a>
        </div>

        @foreach ($organizations as $item)
            <div
                class="border border-slate-300 dark:border-slate-800 dark:bg-slate-800 rounded p-3 mb-4 flex items-center justify-end hover:bg-indigo-100 dark:hover:bg-slate-700">
                <div class="flex-1">
                    <h2 class="font-bold text-medium dark:text-white">{{ $item->name }}</h2>
                    <p class="text-slate-500 text-sm">{{ $item->code }}</p>
                    <span
                        class="text-{{ $item->type == 'Privada' ? 'green' : 'blue' }}-500 font-bold text-sm">{{ $item->type }}</span>
                </div>
                <div class="flex ml-auto">
                    <a href="{{ route('organization.edit', ['organization' => $item->id]) }}"
                        class="text-gray-800 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-4 py-2 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                        <x-pencil-square />
                    </a>
                    <form id="form_delete_{{ $item->id }}"
                        action="{{ route('organization.destroy', ['organization' => $item->id]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                    </form>

                    <button onclick="confirmDelete('form_delete_{{ $item->id }}')"
                        class="text-pink-500 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-4 py-2 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 mr-2 mb-2">
                        <x-trash />
                    </button>
                </div>
            </div>
        @endforeach

    </div>
@endsection